apiVersion: v1
entries:
  clickhouse-cluster:
  - apiVersion: v2
    appVersion: "21.1"
    created: "2022-07-28T20:47:33.20336+08:00"
    description: Helm Chart for deploying a sharded and replicated ClickHouse cluster
      on Kubernetes with Zookeeper
    digest: 0b8b3a33106bfdcd66fb576f01f9119d25e76848270f1dd80b93cc06849ee999
    home: https://github.com/radondb/radondb-clickhouse-kubernetes
    icon: https://xenondb.pek3b.qingstor.com/icons/radondb.svg
    keywords:
    - clickhouse
    maintainers:
    - email: tai_chong@foxmail.com
      name: TCeason
      url: https://tceason.github.io/
    - email: suhouzhen2020@gmail.com
      name: su-houzhen
      url: https://su-houzhen.github.io/
    name: clickhouse-cluster
    sources:
    - https://github.com/radondb/radondb-clickhouse-kubernetes
    type: application
    urls:
    - clickhouse-cluster-v1.0.tgz
    version: v1.0
  dubbo-gui:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-07-28T20:47:33.203992+08:00"
    description: A Helm chart for Kubernetes
    digest: 6f4ba99f0d7d53bb6efa77a6456487aeac1015e8eca247926fcfac9e09d166c8
    name: dubbo-gui
    type: application
    urls:
    - dubbo-gui-0.1.0.tgz
    version: 0.1.0
  elasticsearch:
  - annotations:
      category: Analytics
    apiVersion: v2
    appVersion: 7.17.3
    created: "2022-07-28T20:47:33.21372+08:00"
    dependencies:
    - condition: global.kibanaEnabled
      name: kibana
      repository: https://charts.bitnami.com/bitnami
      version: 9.x.x
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    description: Elasticsearch is a distributed search and analytics engine. It is
      used for web search, log monitoring, and real-time analytics. Ideal for Big
      Data applications.
    digest: 0c625af0b386c67ce7469dc6bd7b4a7a64a618d50dd7db1b950a2920bebba3ef
    home: https://github.com/bitnami/charts/tree/master/bitnami/elasticsearch
    icon: https://bitnami.com/assets/stacks/elasticsearch/img/elasticsearch-stack-220x234.png
    keywords:
    - elasticsearch
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    name: elasticsearch
    sources:
    - https://github.com/bitnami/bitnami-docker-elasticsearch
    - https://www.elastic.co/products/elasticsearch
    urls:
    - elasticsearch-17.9.29.tgz
    version: 17.9.29
  kibana:
  - annotations:
      category: Analytics
    apiVersion: v2
    appVersion: 8.1.3
    created: "2022-07-28T20:47:33.217649+08:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    description: Kibana is an open source, browser based analytics and search dashboard
      for Elasticsearch. Kibana strives to be easy to get started with, while also
      being flexible and powerful.
    digest: 512d62b320105df3e5c668929e946bc95f4f23d9e61f56116bf901cf296139f0
    home: https://github.com/bitnami/charts/tree/master/bitnami/kibana
    icon: https://bitnami.com/assets/stacks/kibana/img/kibana-stack-220x234.png
    keywords:
    - kibana
    - analytics
    - monitoring
    - metrics
    - logs
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    name: kibana
    sources:
    - https://github.com/bitnami/bitnami-docker-kibana
    - https://www.elastic.co/products/kibana
    urls:
    - kibana-10.0.3.tgz
    version: 10.0.3
  logstash:
  - annotations:
      category: LogManagement
    apiVersion: v2
    appVersion: 8.1.3
    created: "2022-07-28T20:47:33.222461+08:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    description: Logstash is an open source data processing engine. It ingests data
      from multiple sources, processes it, and sends the output to final destination
      in real-time. It is a core component of the ELK stack.
    digest: 87d3ae242a9afa3fb8d2eaaf5f59fb9d0459780faad8249504b6dfc23bd6d419
    home: https://github.com/bitnami/charts/tree/master/bitnami/logstash
    icon: https://bitnami.com/assets/stacks/logstash/img/logstash-stack-220x234.png
    keywords:
    - logstash
    - logging
    - elk
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    name: logstash
    sources:
    - https://github.com/bitnami/bitnami-docker-logstash
    - https://www.elastic.co/products/logstash
    urls:
    - logstash-4.0.4.tgz
    version: 4.0.4
  mysql:
  - annotations:
      category: Database
    apiVersion: v2
    appVersion: 8.0.28
    created: "2022-07-28T20:47:33.225631+08:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    description: MySQL is a fast, reliable, scalable, and easy to use open source
      relational database system. Designed to handle mission-critical, heavy-load
      production applications.
    digest: d1043e10fe27730684f5a54c7a58dbf41d3efe1d4f8c7cf9841232ce20277264
    home: https://github.com/bitnami/charts/tree/master/bitnami/mysql
    icon: https://bitnami.com/assets/stacks/mysql/img/mysql-stack-220x234.png
    keywords:
    - mysql
    - database
    - sql
    - cluster
    - high availability
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    name: mysql
    sources:
    - https://github.com/bitnami/bitnami-docker-mysql
    - https://mysql.com
    urls:
    - mysql-8.9.2.tgz
    version: 8.9.2
  nacos:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2022-07-28T20:47:33.226911+08:00"
    description: A Helm chart for Kubernetes
    digest: d912601e60480a9ee83e2ebbebfda762c8054f7e72f8a7d32d270f8f6bf3bfc9
    maintainers:
    - name: arrowfeng
    - name: paderlol
    name: nacos
    urls:
    - nacos-0.1.5.tgz
    version: 0.1.5
  operator:
  - apiVersion: v2
    appVersion: v4.4.22
    created: "2022-07-28T20:47:33.228957+08:00"
    description: A Helm chart for MinIO Operator
    digest: de4bf3143512a6e05b6812742ad3f33b4726d684de381858bcbaf6bc3af96ce8
    home: https://min.io
    icon: https://min.io/resources/img/logo/MINIO_wordmark.png
    keywords:
    - storage
    - object-storage
    - S3
    maintainers:
    - email: dev@minio.io
      name: MinIO, Inc
    name: operator
    sources:
    - https://github.com/minio/operator
    type: application
    urls:
    - operator-4.4.22.tgz
    version: 4.4.22
  redis:
  - annotations:
      category: Database
    apiVersion: v2
    appVersion: 6.2.6
    created: "2022-07-28T20:47:33.234329+08:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    description: Redis(TM) is an open source, advanced key-value store. It is often
      referred to as a data structure server since keys can contain strings, hashes,
      lists, sets and sorted sets.
    digest: 7884d71b540b100b57c80fce99f20ad71e009a5699e1a055adde4a0c171b54cf
    home: https://github.com/bitnami/charts/tree/master/bitnami/redis
    icon: https://bitnami.com/assets/stacks/redis/img/redis-stack-220x234.png
    keywords:
    - redis
    - keyvalue
    - database
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    - email: cedric@desaintmartin.fr
      name: desaintmartin
    name: redis
    sources:
    - https://github.com/bitnami/bitnami-docker-redis
    urls:
    - redis-16.8.7.tgz
    version: 16.8.7
  redis-gui:
  - apiVersion: v2
    created: "2022-07-28T20:47:33.235385+08:00"
    description: A Helm chart for Kubernetes
    digest: e93207383480986d7965897e78359cb1210a16a263d2303cd8d01a070d50e24d
    name: redis-gui
    type: application
    urls:
    - redis-gui-0.1.0.tgz
    version: 0.1.0
  rocketmq:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-07-28T20:47:33.237241+08:00"
    description: A Helm chart for Kubernetes
    digest: 8fce2e843197a48e776eae1e233ac090e8101d0ee70b664e32fc5212702ec2da
    name: rocketmq
    type: application
    urls:
    - rocketmq-0.1.0.tgz
    version: 0.1.0
  tenant:
  - apiVersion: v2
    appVersion: v4.4.22
    created: "2022-07-28T20:47:33.240328+08:00"
    description: A Helm chart for MinIO Operator
    digest: 43a336662999fedb54d94dcfa2c179a8f341163333e9ef7ab16a133f4e7f5463
    home: https://min.io
    icon: https://min.io/resources/img/logo/MINIO_wordmark.png
    keywords:
    - storage
    - object-storage
    - S3
    maintainers:
    - email: dev@minio.io
      name: MinIO, Inc
    name: tenant
    sources:
    - https://github.com/minio/operator
    type: application
    urls:
    - tenant-4.4.22.tgz
    version: 4.4.22
  xxl-job:
  - apiVersion: v2
    appVersion: 2.3.1
    created: "2022-07-28T20:47:33.24083+08:00"
    description: A Helm chart for Kubernetes
    digest: 2a142a6e7e639459c9a4bdef0a1279ab469fc3076009b2114d4a822d747ed530
    name: xxl-job
    type: application
    urls:
    - xxl-job-0.1.0.tgz
    version: 0.1.0
generated: "2022-07-28T20:47:33.201843+08:00"
