apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "redisinsight-chart.fullname" . }}
  labels:
    {{- include "redisinsight-chart.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-storage