apiVersion: v1
kind: Service
metadata:
  name: {{ include "redisinsight-chart.fullname" . }}
  labels:
    {{- include "redisinsight-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      # 此处指定暴露的端口号
      nodePort: {{ .Values.service.nodePort }}
      targetPort: 8001
      protocol: TCP
      name: http
  selector:
    {{- include "redisinsight-chart.selectorLabels" . | nindent 4 }}
